# Publication

## Refereed International Journals
* Dan Davis, Guanliang Chen, Claudia Hauff and Geert-Jan Houben. [Activating Learning at Scale: A Review of Innovations in Online Learning Strategies.](https://www.sciencedirect.com/science/article/pii/S0360131518301337?via%3Dihub) Computers & Education. [\[PDF\]](documents/CE2018-Davis.pdf)
* Guanliang Chen, Dan Davis, Markus Krause, Efthimia Aivaloglou, Claudia Hauff and Geert-Jan Houben (2016). [From Learners to Earners: Enabling MOOC Learners to Apply Their Skills and Earn Money in an Online Market Place.](https://ieeexplore.ieee.org/document/7579220/?arnumber=7579220&source=authoralert) IEEE Transactions on Learning Technologies. [\[PDF\]](documents/TLT16_Guanliang_Can.pdf)
* Guanliang Chen and Li Chen (2015). [Augmenting service recommender systems by incorporating contextual opinions from user reviews.](http://link.springer.com/article/10.1007%2Fs11257-015-9157-3) User Modeling and User-Adapted Interaction Journal (UMUAI). [\[PDF\]](documents/UMUAI15_Guanliang_Augmenting.pdf)
* Li Chen, Guanliang Chen and Feng Wang (2015). [Recommender systems based on user reviews: the state of the art.](http://link.springer.com/article/10.1007%2Fs11257-015-9155-5) User Modeling and User-Adapted Interaction Journal (UMUAI). [\[PDF\]](documents/UMUAI15_Li_Recommender.pdf)


## Refereed International Conferences
* Jionghao Lin, David Lang, Haoran Xie, Dragan Gašević, and Guanliang Chen. Investigating the Role of Politeness in Human-Human Online Tutoring. The International Conference on Artificial Intelligence in Education (AIED), 2020. (Short paper) [\[PDF\]](documents/AIED2020_Jionghao_Investigating.pdf)
* Guanliang Chen, Vitor Rolim, Rafael Ferreira Mello, and Dragan Gašević. [Let’s Shine Together! A Comparative Study between Learning Analytics and Educational Data Mining.](https://dl.acm.org/doi/10.1145/3375462.3375500) The International Conference on Learning Analytics and Knowledge (LAK), 2020. (Full paper) [\[PDF\]](documents/LAK2020_Guanliang_Lets.pdf)
* Máverick Ferreira, Vitor Rolim, Rafael Ferreira Mello, Rafael Lins, Guanliang Chen, and Dragan Gašević. [Towards Automatic Content Analysis of Social Presence in Transcripts of Online Discussions.](https://dl.acm.org/doi/abs/10.1145/3375462.3375495) The International Conference on Learning Analytics and Knowledge (LAK), 2020. (Full paper) [\[PDF\]](documents/LAK2020_Maverick_Towards.pdf)
* David Lang, Guanliang Chen, Kathy Mirzaei, and Andreas Paepcke. [Is Faster Better? A Study of Video Playback Speed.](https://dl.acm.org/doi/10.1145/3375462.3375466) The International Conference on Learning Analytics and Knowledge (LAK), 2020. (Full paper) [\[PDF\]](documents/LAK2020_David_Is.pdf)
* Guanliang Chen, Jie Yang, and Dragan Gašević. [A Comparative Study on Question-worthy Sentence Selection Strategies for Educational Question Generation.](https://link.springer.com/chapter/10.1007/978-3-030-23204-7_6) The International Conference on Artificial Intelligence in Education (AIED), 2019. (Full paper) [\[PDF\]](documents/AIED2019_Guanliang_A.pdf)
* Guanliang Chen, David Lang, Rafael Ferreira Mello, and Dragan Gašević. [Predictors of Student Satisfaction: A Large-scale Study of Human-Human Online Tutorial Dialogues.](https://drive.google.com/file/d/1XdQhaMC-Bke9fmjdArR_n9tm548Er8Md/edit) The International Conference on Educational Data Mining (EDM), 2019. (Full paper) [\[PDF\]](documents/EDM2019_Guanliang_Predictors.pdf)
* Guanliang Chen, Jie Yang, Claudia Hauff and Geert-Jan Houben. [LearningQ: A Large-scale Dataset for Educational Question Generation.](https://aaai.org/ocs/index.php/ICWSM/ICWSM18/paper/view/17857) The AAAI Conference on Web and Social Media (ICWSM), 2018. (Dataset full paper) [\[PDF\]](documents/ICWSM2018_Guanliang_LearningQ.pdf)
* Sepideh Mesbah, Guanliang Chen, Manuel Valle Torre, Alessandro Bozzon, Christoph Lofi, Geert-Jan Houben. [Concept Focus: Semantic Meta-Data for Describing MOOC Content.](https://link.springer.com/chapter/10.1007/978-3-319-98572-5_36) The 13th European Conference on Technology Enhanced Learning (EC-TEL), 2018.
* Yingying Bao, Guanliang Chen and Claudia Hauff. [On the Prevalence of Multiple-Account Cheating in Massive Open Online Learning.](http://educationaldatamining.org/EDM2017/proc_files/papers/paper_91.pdf) The International Conference on Educational Data Mining (EDM), 2017. (Short paper) [\[PDF\]](documents/EDM17_Yingying_Cheating.pdf)
* Dan Davis, Ioana Jivet, René F. Kizilcec, Guanliang Chen, Claudia Hauff and Geert-Jan Houben. [Follow the Successful Crowd: Raising MOOC Completion Rates through Social Comparison at Scale.](http://dl.acm.org/citation.cfm?id=3027411) The International Conference on Learning Analytics and Knowledge (LAK), 2017. [\[PDF\]](documents/LAK17_Dan_Follow.pdf)
* Dan Davis, Guanliang Chen, Tim van der Zee, Claudia Hauff and Geert-Jan Houben. [Retrieval Practice and Study Planning in MOOCs: Exploring Classroom-Based Self-Regulated Learning Strategies at Scale.](http://link.springer.com/chapter/10.1007%2F978-3-319-45153-4_5) The European Conference on Technology-Enhanced Learning (EC-TEL), 2016. \[Best Student Paper Award\] [\[PDF\]](documents/ECTEL16_Dan_Retrieval.pdf)
* Guanliang Chen, Dan Davis, Claudia Hauff and Geert-Jan Houben. [On the Impact of Personality in Massive Open Online Learning.](http://dl.acm.org/citation.cfm?id=2930240) The ACM International Conference on User Modeling, Adaptation and Personalization (UMAP), 2016. [\[PDF\]](documents/UMAP16_Guanliang_Personality.pdf) [\[Slides\]](http://www.slideshare.net/GuanliangChen/on-the-impact-of-personality-in-massive-open-online-learning)
* Dan Davis, Guanliang Chen, Claudia Hauff and Geert-Jan Houben. [Gauging MOOC Learners' Adherence to the Designed Learning Path.](http://www.educationaldatamining.org/EDM2016/proceedings/paper_63.pdf) The International Conference on Educational Data Mining (EDM), 2016. [\[PDF\]](documents/EDM16_Dan_Gauging.pdf)
* Guanliang Chen, Dan Davis, Jun Lin, Claudia Hauff and Geert-Jan Houben. [Beyond the MOOC platform: Gaining Insights aboutLearners from the Social Web.](http://doi.acm.org/10.1145/2908131.2908145) The ACM Conference on Web Science (WebSci), 2016. [\[PDF\]](documents/WEBSCI16_Guanliang_Beyond.pdf) [\[Slides\]](http://www.slideshare.net/GuanliangChen/beyond-the-mooc-platform-gaining-insights-about-learners-from-the-social-web)
* Guanliang Chen, Dan Davis, Claudia Hauff and Geert-Jan Houben. [Learning Transfer: Does It Take Place in MOOCs? An Investigation into the Uptake of Functional Programming in Practice.](http://dl.acm.org/citation.cfm?doid=2876034.2876035) The ACM Conference on Learning at Scale (L@S), 2016. \[Honorable Mention Award\] [\[PDF\]](documents/LS16_Guanliang_Learning.pdf)
* Guanliang Chen and Li Chen. [Recommendation Based on Contextual Opinions.](http://link.springer.com/chapter/10.1007%2F978-3-319-08786-3_6) The International Conference on User Modelling, Adaption and Personalization (UMAP), 2014. \[Best Student Paper Nominee\] [\[PDF\]](documents/UMAP14_Guanliang_Recommendation.pdf)

## -- Editorial Contribution --
* Elle Wang, Dan Davis, Guanliang Chen and Luc Paquette. [Workshop on Integrated Learning Analytics of MOOC Post-Course Development.](https://dl.acm.org/citation.cfm?id=3029430) The International Conference on Learning Analytics and Knowledge (LAK), 2017. [\[PDF\]](documents/LAK17_Elle_Workshop.pdf)

## -- Workshops \& Posters \& Others --
* Guanliang Chen, Claudia Hauff and Geert-Jan Houben. [Feature Engineering for Second Language Acquisition Modeling.](http://sharedtask.duolingo.com/papers/chen.slam18.pdf) Workshop on Innovative Use of NLP for Building Educational Applications, co-located with The North American Chapter of the Association for Computational Linguistics: Human Language Technologies (NAACL-HTL), 2018. (Workshop paper) [\[PDF\]](documents/NAACL-HLT-BEA_Guanliang_Feature.pdf)
* Yue Zhao, Dan Davis, Guanliang Chen, Christoph Lofi, Claudia Hauff and Geert-Jan Houben. [Certificate Achievement Unlocked: Exploring MOOC Learners' Behaviour Before & After Passing.](http://dl.acm.org/citation.cfm?id=3099063) The ACM Conference on User Modeling, Adaptation and Personalization (UMAP), 2017.
* Guanliang Chen, Dan Davis, Markus Krause, Claudia Hauff and Geert-Jan Houben. [Buying Time: Enabling Learners to become Earners with a Real-World Paid Task Recommender System.](http://dl.acm.org/citation.cfm?id=3029469) The International Conference on Learning Analytics and Knowledge (LAK), 2017. (Poster paper) [\[PDF\]](documents/LAK17_Guanliang_Buying.pdf)
* Dan Davis, Guanliang Chen, Ioana Jivet, Claudia Hauff and Geert-Jan Houben. [Encouraging Metacognition & Self-Regulation in MOOCs through Increased Learner Feedback.](http://ceur-ws.org/Vol-1596/paper3.pdf) Workshop on Learning Analytics for Learners, co-located with The International Conference on Learning Analytics and Knowledge (LAK), 2016. [\[PDF\]](documents/LAK16_Dan_Encouraging.pdf)
* Jian Chen, Guanliang Chen, Haolan Zhang, Jin Huang and Gansen Zhao. [Social Recommendation Based on Multi-relational Analysis.](http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=6511610&url=http%3A%2F%2Fieeexplore.ieee.org%2Fxpls%2Fabs_all.jsp%3Farnumber%3D6511610) The IEEE/WIC/ACM International Conferences on Web Intelligence and Intelligent Agent Technology (WI-IAT), 2012. [\[PDF\]](documents/WI12_Jian_Social.pdf)
